import { asset } from '../utils/asset-map'
import { AI_CHESS_LAB_INTRO_TOPICS } from './ai-chess-lab-topics'

const AI_MAJOR_WEB_ALIGNED_BLUEPRINT = {
  label: '人工智能',
  labelLong: '计算机学院人工智能专业',
  en: 'Artificial Intelligence',
  accent: '#14b8a6',
  intro: [
    '人工智能研究如何让机器感知、学习、推理、生成和决策。它把数学基础、数据处理、模型训练、系统工程和评测治理组织成一条可验证的技术链。',
    '计算机学院的人工智能专业通常会从程序、数据结构、机器学习和深度学习进入，再分流到大模型应用、AI 系统、具身智能、AI 安全与行业落地。',
  ],
  overviewCards: [
    { title: '人工智能学什么', body: '从程序、数据、模型、系统和评测理解智能如何被实现。' },
    { title: '四年课程地图', body: '编程基础 -> 机器学习 -> 深度学习 -> 大模型、系统与行业分流。' },
    { title: '真实工作对象', body: '数据集、训练脚本、评测报告、推理服务、提示词和安全审查。' },
    { title: '毕业去向', body: '算法工程、LLM 应用工程、AI 系统、AI 安全、机器人和研究生路线。' },
  ],
  foundationIntro: '基础内容先建立编程、数据结构、概率统计和线性代数底座，让学生能把问题写成可计算形式。',
  coreIntro: '专业内容进入机器学习、深度学习、计算机视觉、自然语言处理、强化学习、AI 系统与大模型应用。',
  foundationCourses: [
    {
      id: 'ai-introduction',
      title: '人工智能导论',
      subtitle: '从“会写程序”走到“会做智能系统”',
      intro: '沿着规则系统、搜索、机器学习和大模型四条线，理解人工智能为什么会从“编答案”变成“学规律”。',
      topics: ['符号主义 AI', '专家系统 AI', '搜索 AI 与优化搜索', '机器学习评价函数', '神经网络', '现代大语言模型'],
      task: '判断一个小型 AI 系统在数据、规则、算力和评测上的边界',
      tags: ['AI 历史', '机器学习', '大模型'],
      chessLabTopics: AI_CHESS_LAB_INTRO_TOPICS,
    },
    {
      id: 'ai-programming-data-structures',
      title: '编程与数据结构',
      subtitle: '让算法真正跑起来',
      intro: '把问题写成代码、把数据组织成结构、把流程变成可执行程序，是 AI 学习的第一步。',
      topics: ['Python/Java 基础', '数组与链表', '栈队列', '树与图', '递归与复杂度'],
      task: '实现一个简单搜索或分类小程序并补全测试',
      tags: ['编程', '数据结构', '复杂度'],
    },
    {
      id: 'ai-probability-linear-algebra',
      title: '概率统计与线性代数',
      subtitle: 'AI 的数学底座',
      intro: '用向量、矩阵、分布、期望和梯度理解模型是怎么从数据里学东西的。',
      topics: ['向量与矩阵', '特征值直觉', '概率分布', '统计估计', '梯度与优化'],
      task: '把一个数据集做成特征矩阵并解释训练误差',
      tags: ['数学基础', '概率', '矩阵'],
    },
  ],
  coreCourses: [
    {
      id: 'ai-machine-learning',
      title: '机器学习',
      subtitle: '让模型从数据中找规律',
      intro: '从特征、损失函数、泛化和过拟合进入监督学习、无监督学习和模型评估。',
      topics: ['回归与分类', '树模型', 'SVM', '聚类', '交叉验证'],
      task: '训练一个分类器并分析错误样本',
      tags: ['ML', '泛化', '评估'],
    },
    {
      id: 'ai-deep-learning',
      title: '深度学习',
      subtitle: '神经网络如何表达复杂模式',
      intro: '连接反向传播、卷积、注意力、序列建模和生成模型，理解模型结构为什么有效。',
      topics: ['反向传播', 'CNN', 'RNN/Transformer', '损失函数', '生成模型'],
      task: '复现一个小型神经网络任务并记录指标',
      tags: ['DL', 'Transformer', '生成'],
    },
    {
      id: 'ai-systems-llm',
      title: 'AI 系统与大模型应用',
      subtitle: '把模型变成产品和服务',
      intro: '把训练、推理、部署、缓存、检索增强和评测放进真实工程流程。',
      topics: ['推理服务', 'RAG', 'Agent', 'MLOps', '安全与评测'],
      task: '设计一个可演示的 LLM 应用流程',
      tags: ['LLM', 'MLOps', '应用'],
    },
  ],
  branches: [
    {
      id: 'ai-agent',
      title: '大模型应用与 Agent',
      fit: '喜欢把模型接入工具和业务流程',
      topics: ['提示词工程', 'Agent 工作流'],
      frontier: 'MCP、工具调用、SWE-bench、RAG 评测',
      project: '做一个能完成任务的校园助手',
      roles: ['LLM 应用工程'],
    },
    {
      id: 'ai-vision-nlp',
      title: '视觉与自然语言处理',
      fit: '喜欢图像、文本和多模态',
      topics: ['计算机视觉', 'NLP'],
      frontier: '检测、分割、检索增强、多模态模型',
      project: '做一个图文理解或问答小系统',
      roles: ['算法工程', 'CV/NLP'],
    },
    {
      id: 'ai-robotics',
      title: '机器人与具身智能',
      fit: '喜欢真实环境、控制和反馈',
      topics: ['机器人感知', '控制与规划'],
      frontier: 'ROS2、仿真、具身评测',
      project: '完成一个简单机器人任务策略',
      roles: ['机器人 AI'],
    },
    {
      id: 'ai-safety-industry',
      title: 'AI 安全、评测与行业应用',
      fit: '喜欢测试边界和治理',
      topics: ['评测体系', '安全治理'],
      frontier: '模型卡、红队、NIST AI RMF、OWASP LLM',
      project: '为一个 LLM 应用写风险与评测报告',
      roles: ['AI 安全', '行业 AI 工程'],
    },
  ],
  careers: ['算法工程', 'LLM 应用工程', 'AI 系统工程', 'AI 安全评测', '研究生路线'],
}

const AI_MAJOR_COMPAT_FIELDS = {
  summary: AI_MAJOR_WEB_ALIGNED_BLUEPRINT.intro[0],
  fit: [
    '愿意把数学、数据与代码组织成可验证的训练流程',
    '对模型训练、评测治理、系统落地和失败分析有兴趣',
    '能接受高反馈密度的迭代学习，并持续复盘模型边界',
  ],
  coreCourses: AI_MAJOR_WEB_ALIGNED_BLUEPRINT.foundationCourses
    .concat(AI_MAJOR_WEB_ALIGNED_BLUEPRINT.coreCourses)
    .map((course) => course.title),
  directions: AI_MAJOR_WEB_ALIGNED_BLUEPRINT.branches.map((branch) => branch.title),
  tasks: [
    '先建立人工智能专业认知，确认它不是“调用模型”，而是完整的技术训练链。',
    '再沿着基础课和核心课观察自己是否真的喜欢数据、模型、系统与评测工作。',
    '最后比较不同分流方向，判断自己更适合应用、算法、系统、机器人还是治理路线。',
  ],
}

export const DISCOVER_STAGES = [
  {
    id: 'personality',
    number: '01',
    stageTitle: '第一阶段 性格测试',
    title: '性格测试',
    intro: '先完成 MBTI 性格测试，建立你的基础行为风格画像。',
    lines: ['完成 MBTI 题组', '确认行为风格画像'],
    progressLabel: '性格测试进度',
    actionLabel: '开始测试',
    accent: '#14b8a6',
    track: '#087c72',
    fill: '#19d0b0',
    knob: '#4de5cf',
    soft: '#ebfffb',
    artwork: 'https://uniprism.cn/images/explore/discover/generated/interest-stage-student-simple-crop.png',
  },
  {
    id: 'career',
    number: '02',
    stageTitle: '第二阶段 职业测评',
    title: '职业测评',
    intro: '完成 Holland/RIASEC 职业兴趣量表，识别更稳定的职业兴趣方向。',
    lines: ['完成 60 道职业兴趣题', '获得职业兴趣维度结果'],
    progressLabel: '职业测评进度',
    actionLabel: '开始测评',
    accent: '#2BA8BC',
    track: '#0b65c2',
    fill: '#76d8ff',
    knob: '#a8ecff',
    soft: '#f1fcfe',
    artwork: 'https://uniprism.cn/images/explore/discover/generated/stage-major-experience-crop.png',
  },
  {
    id: 'deep',
    number: '03',
    stageTitle: '第三阶段 深度测评',
    title: '深度测评',
    intro: '结合细分维度题与职业校准题，确认价值观和真实偏好。',
    lines: ['完成深度细分题', '完成最终职业校准'],
    progressLabel: '深度测评完成度',
    actionLabel: '进入测评',
    accent: '#8b5cf6',
    track: '#5537c8',
    fill: '#ffb020',
    knob: '#ffd27a',
    soft: '#f7f3ff',
    artwork: 'https://uniprism.cn/images/explore/discover/generated/stage-career-simulation-crop.png',
  },
  {
    id: 'report',
    number: '04',
    title: '生成报告',
    intro: '汇总性格测试、职业测评与深度测评结果，生成最终报告。',
    actionLabel: '查看探索报告',
    accent: '#f59e0b',
    soft: '#fff8ec',
    artwork: asset('/images/explore/discover/step-report-bg.png'),
  },
]

export const INTEREST_SHORTCUTS = [
  {
    id: 'profile',
    icon: asset('/images/explore/discover/sidebar/profile.png'),
    title: '查看个人画像',
    subtitle: '查看内容',
    lockUntilProfile: true,
  },
  {
    id: 'major',
    icon: 'https://uniprism.cn/images/explore/discover/generated/learn-majors-card-icon-v1.png',
    title: '了解不同专业',
    subtitle: '查看内容',
  },
  {
    id: 'career',
    icon: 'https://uniprism.cn/images/explore/discover/generated/learn-careers-card-icon-v1.png',
    title: '了解不同职业',
    subtitle: '查看内容',
  },
]

export const MAJOR_TASK_OVERVIEW = {
  title: '四阶段测评概览',
  badge: '当前阶段',
  description: '按顺序完成性格测试、职业测评、深度测评，再生成最终报告。',
  visualBefore: 'https://uniprism.cn/images/explore/discover/generated/task-interest-model.png',
  visualAfter: 'https://uniprism.cn/images/explore/discover/generated/task-interest-model.png',
  footerLines: [
    '在进入最终报告前，你会依次完成三段测评内容。',
    '系统会基于完整答题结果汇总你的画像、推荐方向和发展建议。',
  ],
}

export const MAJOR_EXPERIENCES = [
  {
    id: 'math-u',
    title: '数学与应用数学',
    shortTitle: '数学',
    en: 'Mathematics',
    accent: '#1769E0',
    icon: asset('/images/explore/discover/figma/major-math-345-32973.svg'),
    heroImage: asset('/images/explore/discover/stage-hero-major-clean.png'),
    summary: '用函数、结构与推理理解世界，建立抽象建模与严谨证明能力。',
    fit: ['喜欢从定义出发推导结论', '愿意用模型解释复杂现象', '能接受较长的训练周期'],
    coreCourses: ['数学分析', '线性代数', '概率论', '抽象代数', '拓扑学'],
    directions: ['基础数学', '应用数学', '计算数学', '统计', '金融数学'],
    careers: ['数学家', '算法研究员', '量化分析师', '软件工程师'],
    tasks: ['了解数学专业概览与课程结构', '阅读基础课与深入方向内容', '完成数学分析挑战并选择分流方向'],
    media: [
      { type: 'image', url: 'https://uniprism.cn/design/math-speed/generated/math-branching-start-v1.png', title: '专业分流图' },
      { type: 'image', url: 'https://uniprism.cn/design/math-speed/generated/math-intro-home-curriculum-v5.png', title: '课程路径图' },
    ],
    route: '/subpkg/math/deep-explore',
  },
  {
    id: 'physics-u',
    title: '物理学',
    shortTitle: '物理学',
    en: 'Physics',
    accent: '#06b6d4',
    icon: asset('/images/explore/discover/figma/major-physics-345-32972.svg'),
    heroImage: 'https://uniprism.cn/design/major-sim/physics/foundation/mechanics-model-cn-v2.png',
    summary: '从普通物理基础进入理论、实验和计算训练，适合愿意用模型和证据解释自然现象的人。',
    fit: ['对自然规律有强烈好奇', '愿意在实验和理论之间切换', '擅长用数学表达现实问题'],
    coreCourses: ['力学', '电磁学', '热力学与统计物理', '光学与量子基础'],
    directions: ['理论物理', '实验物理', '计算物理', '交叉科学'],
    careers: ['科研计算', '算法研究', '高端制造研发'],
    tasks: ['理解基础课程结构', '查看典型实验与建模图', '判断自己更偏理论还是实验'],
    media: [
      { type: 'image', url: 'https://uniprism.cn/design/major-sim/physics/foundation/mechanics-model-cn-v2.png', title: '力学建模' },
      { type: 'image', url: 'https://uniprism.cn/design/major-sim/physics/foundation/electromagnetism-overview-cn-v2.png', title: '电磁学总览' },
    ],
  },
  {
    id: 'cs-u',
    title: '计算机科学',
    shortTitle: '计算机',
    en: 'Computer Science',
    accent: '#5b6cff',
    icon: asset('/images/explore/discover/icons/generated/discover-major-computer-science-technology-20260610-v2-flat2d.png'),
    heroImage: 'https://uniprism.cn/design/major-sim/cs/foundation/algorithms-data-structures-v1.png',
    summary: '从程序、离散结构和算法进入系统课程，适合愿意证明过程正确并诊断真实系统约束的人。',
    fit: ['喜欢结构化解决问题', '愿意反复调试和验证', '对系统如何运转有兴趣'],
    coreCourses: ['程序设计', '离散数学', '数据结构与算法', '操作系统'],
    directions: ['软件系统', '安全', '系统架构', '应用算法'],
    careers: ['软件工程师', '算法研究员', '系统开发'],
    tasks: ['查看算法与系统训练图', '比较不同方向输出', '评估自己更喜欢抽象推理还是工程落地'],
    media: [
      { type: 'image', url: 'https://uniprism.cn/design/major-sim/cs/foundation/algorithms-data-structures-v1.png', title: '算法与数据结构' },
      { type: 'image', url: 'https://uniprism.cn/design/major-sim/cs/foundation/systems-networks-v1.png', title: '系统与网络' },
    ],
  },
  {
    id: 'ai-u',
    title: '人工智能',
    shortTitle: '人工智能',
    en: 'Artificial Intelligence',
    accent: '#14b8a6',
    icon: asset('/images/explore/discover/icons/generated/discover-major-artificial-intelligence-20260610-v2-flat2d.png'),
    heroImage: 'https://uniprism.cn/design/major-sim/ai/generated/ai-overview-hero-v2.png',
    labelLong: AI_MAJOR_WEB_ALIGNED_BLUEPRINT.labelLong,
    intro: AI_MAJOR_WEB_ALIGNED_BLUEPRINT.intro,
    overviewCards: AI_MAJOR_WEB_ALIGNED_BLUEPRINT.overviewCards,
    foundationIntro: AI_MAJOR_WEB_ALIGNED_BLUEPRINT.foundationIntro,
    coreIntro: AI_MAJOR_WEB_ALIGNED_BLUEPRINT.coreIntro,
    foundationCoursesDetail: AI_MAJOR_WEB_ALIGNED_BLUEPRINT.foundationCourses,
    coreCoursesDetail: AI_MAJOR_WEB_ALIGNED_BLUEPRINT.coreCourses,
    branchDirectionsDetail: AI_MAJOR_WEB_ALIGNED_BLUEPRINT.branches,
    webAligned: AI_MAJOR_WEB_ALIGNED_BLUEPRINT,
    summary: AI_MAJOR_COMPAT_FIELDS.summary,
    fit: AI_MAJOR_COMPAT_FIELDS.fit,
    coreCourses: AI_MAJOR_COMPAT_FIELDS.coreCourses,
    directions: AI_MAJOR_COMPAT_FIELDS.directions,
    careers: AI_MAJOR_WEB_ALIGNED_BLUEPRINT.careers,
    tasks: AI_MAJOR_COMPAT_FIELDS.tasks,
    media: [
      { type: 'image', url: 'https://uniprism.cn/design/major-sim/ai/generated/ai-overview-hero-v2.png', title: 'AI 总览' },
      { type: 'image', url: 'https://uniprism.cn/design/major-sim/ai/generated/ai-course-map-v2.png', title: '课程地图' },
    ],
    route: '/subpkg/discover/major-speed?id=ai-u',
  },
  {
    id: 'finance-u',
    title: '金融学院',
    shortTitle: '金融学',
    en: 'Finance',
    accent: '#4477ff',
    icon: asset('/images/explore/discover/icons/generated/discover-major-finance-20260608-v1.png'),
    heroImage: asset('/images/explore/discover/stage-hero-major-clean.png'),
    summary: '理解资金流动、现金流、时间价值、风险收益和企业融资选择。',
    fit: ['对数据和商业判断都敏感', '愿意理解市场波动', '喜欢风险与收益分析'],
    coreCourses: ['公司金融', '投资学', '计量分析', '风险管理'],
    directions: ['投资研究', '量化金融', '金融科技', '监管与风控'],
    careers: ['投资分析师', '量化研究员', '金融产品经理'],
    tasks: ['理解资金选择与现金流', '体验时间价值与融资取舍', '完成章末测验'],
    media: [
      { type: 'image', url: asset('/images/explore/discover/stage-hero-major-clean.png'), title: '金融学院' },
    ],
    route: '/subpkg/discover/business-major-speed?id=finance-u',
  },
  {
    id: 'econ-u',
    title: '经济学院',
    shortTitle: '经济学',
    en: 'Economics',
    accent: '#f3a43b',
    icon: asset('/images/explore/discover/icons/generated/discover-major-economics-20260610-v2-flat2d.png'),
    heroImage: asset('/images/explore/discover/stage-hero-major-clean.png'),
    summary: '从稀缺、机会成本、边际思维到供需与均衡，体验经济学如何解释选择。',
    fit: ['喜欢解释社会运行机制', '能接受抽象模型与数据并行', '对政策和产业有兴趣'],
    coreCourses: ['微观经济学', '宏观经济学', '计量经济学', '博弈论'],
    directions: ['政策研究', '产业分析', '数据研究', '商业策略'],
    careers: ['经济研究员', '产业分析师', '咨询顾问'],
    tasks: ['理解稀缺与机会成本', '体验供需与均衡案例', '完成章末测验'],
    media: [
      { type: 'image', url: asset('/images/explore/discover/stage-hero-major-clean.png'), title: '经济学院' },
    ],
    route: '/subpkg/discover/business-major-speed?id=econ-u',
  },
  {
    id: 'marketing-u',
    title: '营销学院',
    shortTitle: '市场营销',
    en: 'Marketing',
    accent: '#d86975',
    icon: asset('/images/explore/discover/icons/generated/discover-major-marketing-20260608-v1.png'),
    heroImage: asset('/images/explore/discover/stage-hero-major-clean.png'),
    summary: '从顾客洞察、STP 到 4P，练习把产品价值传递给正确的人。',
    fit: ['喜欢理解顾客需求', '愿意做策略与传播结合', '对品牌与增长有兴趣'],
    coreCourses: ['市场营销学', '消费者行为', '品牌管理', '数字营销'],
    directions: ['品牌策略', '数字营销', '产品营销', '增长运营'],
    careers: ['品牌经理', '数字营销专员', '产品经理'],
    tasks: ['理解 STP 与 4P', '体验营销一致性判断', '完成章末测验'],
    media: [
      { type: 'image', url: asset('/images/explore/discover/stage-hero-major-clean.png'), title: '营销学院' },
    ],
    route: '/subpkg/discover/business-major-speed?id=marketing-u',
  },
  {
    id: 'actuarial-u',
    title: '精算学',
    shortTitle: '精算学',
    en: 'Actuarial Science',
    accent: '#0f766e',
    icon: asset('/images/explore/discover/icons/generated/majors/major-actuarial.svg'),
    heroImage: asset('/images/explore/discover/stage-hero-major-clean.png'),
    summary: '把概率、金融数学、保险业务和资本监管组织成不确定现金流的定价与准备。',
    fit: ['对概率与风险很敏感', '偏好严谨规范的分析工作', '愿意长期训练数理能力'],
    coreCourses: ['概率论', '金融数学', '保险学', '风险建模'],
    directions: ['保险定价', '风险评估', '资本管理', '数据风控'],
    careers: ['精算分析师', '风险经理', '保险产品研究'],
    tasks: ['理解定价逻辑', '比较风险控制与业务应用', '判断自己是否喜欢规范型工作'],
    media: [
      { type: 'image', url: asset('/images/explore/discover/stage-hero-major-clean.png'), title: '专业入口' },
    ],
  },
  {
    id: 'chem-u',
    title: '化学',
    shortTitle: '化学',
    en: 'Chemistry',
    accent: '#ea580c',
    icon: asset('/images/explore/discover/icons/generated/majors/major-chemistry.svg'),
    heroImage: asset('/images/explore/discover/stage-hero-major-clean.png'),
    summary: '从结构、反应、谱图和安全记录进入材料能源、药物、分析和绿色化学方向。',
    fit: ['喜欢观察物质变化', '愿意遵守实验规范', '对材料或生命应用感兴趣'],
    coreCourses: ['无机化学', '有机化学', '分析化学', '物理化学'],
    directions: ['材料化学', '药物研发', '分析检测', '绿色化学'],
    careers: ['材料研发', '药物研究', '实验分析工程师'],
    tasks: ['了解实验训练强度', '比较不同应用方向', '判断自己是否喜欢实验室环境'],
    media: [
      { type: 'image', url: asset('/images/explore/discover/stage-hero-major-clean.png'), title: '专业入口' },
    ],
  },
  {
    id: 'bio-u',
    title: '生物学',
    shortTitle: '生物',
    en: 'Biology',
    accent: '#22c55e',
    icon: asset('/images/explore/discover/figma/major-biology-345-32970.svg'),
    heroImage: asset('/images/explore/discover/stage-hero-major-clean.png'),
    summary: '从细胞、遗传、生态和实验设计进入生命科学、医学转化和生物技术方向。',
    fit: ['对生命系统有持续好奇', '愿意做观察记录与实验验证', '能接受长期积累和反复复核'],
    coreCourses: ['细胞生物学', '遗传学', '生物化学', '生态学'],
    directions: ['分子生物', '生物技术', '生态与环境', '医学相关研究'],
    careers: ['生物研发', '实验研究员', '医学与健康相关分析'],
    tasks: ['理解生命科学训练路径', '比较实验与应用方向', '判断自己是否喜欢持续观察和验证'],
    media: [
      { type: 'image', url: asset('/images/explore/discover/stage-hero-major-clean.png'), title: '专业入口' },
    ],
  },
  {
    id: 'mech-u',
    title: '机械工程',
    shortTitle: '机械工程',
    en: 'Mechanical Engineering',
    accent: '#475569',
    icon: asset('/images/explore/discover/icons/generated/majors/major-mechanical.svg'),
    heroImage: asset('/images/explore/discover/stage-hero-major-clean.png'),
    summary: '把力学、材料、热流体、控制和制造约束变成可验证、可量产的机械系统。',
    fit: ['喜欢实体系统和结构', '愿意在约束下做设计', '重视可制造性与可靠性'],
    coreCourses: ['工程力学', '机械设计', '材料基础', '制造工艺'],
    directions: ['结构设计', '制造系统', '自动化设备', '工业研发'],
    careers: ['机械设计工程师', '产品研发工程师', '制造工程师'],
    tasks: ['理解工程约束', '比较设计与制造角色', '判断自己是否喜欢硬件系统'],
    media: [
      { type: 'image', url: asset('/images/explore/discover/stage-hero-major-clean.png'), title: '专业入口' },
    ],
  },
  {
    id: 'ee-u',
    title: '电子电器',
    shortTitle: '电子电器',
    en: 'Electrical and Electronic Engineering',
    accent: '#2563eb',
    icon: asset('/images/explore/discover/icons/generated/majors/major-ee.svg'),
    heroImage: asset('/images/explore/discover/stage-hero-major-clean.png'),
    summary: '从电路、信号、逻辑、嵌入式和电磁功率进入通信、控制、板级硬件与测试。',
    fit: ['喜欢电路和系统联动', '能处理抽象信号与真实硬件', '愿意调试复杂设备'],
    coreCourses: ['电路基础', '信号与系统', '嵌入式系统', '控制原理'],
    directions: ['通信', '控制', '嵌入式', '硬件测试'],
    careers: ['硬件工程师', '嵌入式开发', '控制系统工程师'],
    tasks: ['理解信号与硬件关系', '比较不同工程方向', '判断自己更偏底层还是系统'],
    media: [
      { type: 'image', url: asset('/images/explore/discover/stage-hero-major-clean.png'), title: '专业入口' },
    ],
  },
  {
    id: 'ic-u',
    title: '集成电路',
    shortTitle: '集成电路',
    en: 'Integrated Circuit',
    accent: '#7c3aed',
    icon: asset('/images/explore/discover/icons/generated/majors/major-ic.svg'),
    heroImage: asset('/images/explore/discover/stage-hero-major-clean.png'),
    summary: '从半导体器件、RTL、验证、后端和封装约束进入芯片设计与 AI 加速器方向。',
    fit: ['对底层硬件逻辑敏感', '愿意处理复杂约束和长周期项目', '喜欢高精度协作'],
    coreCourses: ['数字电路', '半导体器件', '芯片设计', '验证与后端'],
    directions: ['数字前端', '验证', '后端实现', 'AI 芯片'],
    careers: ['芯片设计工程师', '验证工程师', 'EDA 研发'],
    tasks: ['了解芯片开发流程', '比较前后端角色', '判断自己是否适合高约束协作环境'],
    media: [
      { type: 'image', url: asset('/images/explore/discover/stage-hero-major-clean.png'), title: '专业入口' },
    ],
  },
]

export const CAREER_SIMULATIONS = [
  {
    id: 'mathematician',
    title: '数学家',
    badge: '纯粹研究',
    track: '理科',
    accent: '#3b82f6',
    icon: asset('/images/explore/discover/icons/generated/careers/career-mathematician.png'),
    heroImage: asset('/images/careers/simulation-mathematician.png'),
    summary: '从结构、证明与抽象系统中寻找新的知识边界。',
    dimensions: ['I', 'C'],
    relatedMajors: ['math-u', 'physics-u', 'cs-u'],
    steps: [
      { title: '认识工作对象', body: '数学家的任务不是做现成题目，而是把模糊直觉改写成可验证的命题与证明。', image: asset('/images/careers/simulation-mathematician.png') },
      { title: '拆解研究流程', body: '先读文献、找例子、看边界，再把问题压缩成局部命题，逐步形成证明。', image: 'https://uniprism.cn/design/math-speed/generated/math-logic-article-proof-bw-v2.png' },
      { title: '进入情境任务', body: '面对一个图结构猜想，判断先找反例、先做特例，还是先补背景。', image: asset('/images/explore/discover/career-simulation/scenario-to-task.png') },
      { title: '形成适配判断', body: '最终回到一个核心问题：你是否愿意长期面对不确定、反复打磨表达与证明。', image: asset('/images/explore/discover/career-simulation/choice-to-fit.png') },
    ],
  },
  {
    id: 'algorithm-researcher',
    title: '算法研究员',
    badge: '算法设计',
    track: '交叉',
    accent: '#00a889',
    icon: asset('/images/explore/discover/icons/generated/careers/career-algorithm-researcher.png'),
    heroImage: asset('/images/explore/discover/stage-hero-career-clean.png'),
    summary: '在图结构、复杂度与最优路径中验证更高效的解决方案。',
    dimensions: ['I', 'C'],
    relatedMajors: ['cs-u', 'ai-u', 'math-u'],
    steps: [
      { title: '理解问题形态', body: '算法研究员把现实任务翻译成搜索、优化、预测或决策问题。', image: 'https://uniprism.cn/design/major-sim/cs/foundation/algorithms-data-structures-v1.png' },
      { title: '比较解决策略', body: '你要在精确性、速度、资源消耗和泛化能力之间做取舍。', image: 'https://uniprism.cn/design/major-sim/ai/foundation/training-loop-v1.png' },
      { title: '模拟研究节奏', body: '从 baseline 到误差分析，再到模型迭代，真正的工作是持续判断。', image: 'https://uniprism.cn/design/major-sim/ai/foundation/knowledge-search-v1.png' },
    ],
  },
  {
    id: 'software-engineer',
    title: '软件工程师',
    badge: '系统构建',
    track: '工科',
    accent: '#5b6cff',
    icon: asset('/images/explore/discover/icons/generated/careers/career-software-engineer.png'),
    heroImage: asset('/images/explore/discover/stage-hero-career-clean.png'),
    summary: '把模块、接口与调试反馈组织成稳定可用的软件系统。',
    dimensions: ['R', 'I', 'C'],
    relatedMajors: ['cs-u', 'ai-u', 'ee-u'],
    steps: [
      { title: '认识系统约束', body: '软件工程师不仅写功能，还要处理性能、稳定性、协作和可维护性。', image: 'https://uniprism.cn/design/major-sim/cs/foundation/systems-networks-v1.png' },
      { title: '搭建实现路径', body: '需求拆解、接口定义、测试验证、日志诊断构成了核心工作流。', image: 'https://uniprism.cn/design/major-sim/cs/foundation/algorithms-data-structures-v1.png' },
      { title: '判断职业适配', body: '如果你喜欢通过迭代把复杂系统打磨成可用产品，这条路径会更匹配你。', image: asset('/images/explore/discover/stage-hero-career-clean.png') },
    ],
  },
]

export function getMajorById(majorId) {
  return MAJOR_EXPERIENCES.find((item) => item.id === majorId) || null
}

export function getCareerById(careerId) {
  return CAREER_SIMULATIONS.find((item) => item.id === careerId) || null
}

export function getRecommendedCareers(topDimensions, recommendedMajorIds) {
  const dims = topDimensions || []
  const majors = recommendedMajorIds || []
  return CAREER_SIMULATIONS
    .map((career) => {
      let score = 0
      ;(career.dimensions || []).forEach((dim) => {
        if (dims.includes(dim)) score += 2
      })
      ;(career.relatedMajors || []).forEach((majorId) => {
        if (majors.includes(majorId)) score += 3
      })
      if (career.id === 'mathematician' && dims.includes('I')) score += 1
      return { ...career, _score: score }
    })
    .sort((a, b) => b._score - a._score)
}
